### ISSUE TITLE
Setup Project Environment

### ISSUE THREAD

**Issue by Sylvain-Chu** [Sylvain-Chu/chess-sisi-bot#1]
# Setup Project Environment

- Initialize a new Nuxt 3 project.
- Install necessary dependencies such as `vue3-chessboard`.

## Tasks
- [x] Create a new Nuxt 3 project.
- [x] Install `vue3-chessboard`.
- [x] Verify the setup by running the development server.
