### ISSUE TITLE
Integrate Stockfish.js for Stronger AI

### ISSUE THREAD

**Issue by Sylvain-Chu** [Sylvain-Chu/chess-sisi-bot#10]
# Integrate Stockfish.js for Stronger AI

- Integrate Stockfish.js to provide a stronger AI opponent.
- Allow users to choose to play against Stockfish.

## Tasks
- [ ] Install and set up Stockfish.js.
- [ ] Integrate Stockfish.js with the chessboard.
- [ ] Test the integration by playing against Stockfish.
