### ISSUE TITLE
Design Chessboard Interface

### ISSUE THREAD

**Issue by Sylvain-Chu** [Sylvain-Chu/chess-sisi-bot#3]
# Design Chessboard Interface

- Apply styles to the chessboard to make it visually appealing.
- Use the design aesthetics similar to chess.com.

## Tasks
- [x] Create a CSS file or use scoped styles in `ChessBoard.vue`.
- [x] Apply styles to the chessboard for a visually appealing design.
- [x] Ensure the design is responsive and looks good on different screen sizes.
