### ISSUE TITLE
Fetch and Display Chess.com Games

### ISSUE THREAD

**Issue by Sylvain-Chu** [Sylvain-Chu/chess-sisi-bot#5]
# Fetch and Display Chess.com Games

- Integrate with Chess.com API to fetch user's games.
- Display a list of games for the user to select and import.

## Tasks
- [ ] Create a service to fetch games from Chess.com API.
- [ ] Display fetched games in a list format.
- [ ] Allow user to select and import a game to replay.
