### ISSUE TITLE
Enhance AI with User's Chess.com Games

### ISSUE THREAD

**Issue by Sylvain-Chu** [Sylvain-Chu/chess-sisi-bot#8]
# Enhance AI with User's Chess.com Games

- Analyze the user's games from Chess.com.
- Train the AI to mimic the user's playing style.

## Tasks
- [ ] Implement a function to analyze user's games.
- [ ] Enhance the AI to use this analysis for decision making.
- [ ] Test the AI to ensure it plays similarly to the user.
